### ISSUE TITLE
would not install on X7.4

### ISSUE THREAD

**Issue by pedrungbako** [JonnoFTW/BibTeX-Label-Creator#3]
Tried it on Windows10 running on Parallels in El Capitan. Placed the file in every folder that can possibly contain .dll files but had no luck.

not sure if this is a win10 issue or x7.4 with the plugin

**Comment by JonnoFTW** [comment]
So you tried in the my documents folder and the program plugins folder? I don't have access to a win10 machine and I haven't tried on the latest version of endnote so I can't really investigate.

**Comment by pedrungbako** [comment]
Yes I did. which version of endnote does it work on?

Thanks!

**Comment by GilmourR** [comment]
Not loading on X7.4 on Windows 7. Tried my documents\endnote\plugins as well as program files\endnote\plugins and program files\endnote.  The loading function appears to be performed by Thomson's RSServices in EntryExit.cpp. Is something broken here?

**Comment by JonnoFTW** [comment]
I haven't changed anything. I'll look into this issue, perhaps the SDK has been updated. The plugin might also need to be compiled with a newer compiler.

**Comment by GilmourR** [comment]
I discovered my DLL file was incomplete. The checksum is  C0C4850803F72D99287B2608CD0E6F9B and the file size is 257,536 bytes. After downloading the BibTeX-Label-Creator.dll file again, I put it in C:\Program Files (x86)\EndNote X7\Plugins.  The plugin then loaded under the "Tools" menu item and generated the labels as required. Thank you very much for the plugin. It saved me a lot of typing.
