### ISSUE TITLE
EndNote X7 Windows10

### ISSUE THREAD

**Issue by dcgemperline** [JonnoFTW/BibTeX-Label-Creator#4]
Hello, 

For whatever reason, the dll version you have pre-compiled won't work with Win10. I have compiled a Win10 version that seemed to work for me. It took a bit of work setting up the right compile settings and getting visual studio associated with boost. I was able to compile with VisualStudio2015 and the boost libraries you specified with some tweaks. You may want to update your binaries if possible.

David

**Comment by JonnoFTW** [comment]
If you submit a pull request with the dll file I'll accept it.

**Comment by HJAllen** [comment]
It looks like the Win10 dll was not provided. Is it possible to get a working Win10 version without compiling myself?
Thanks for all your efforts.

**Comment by dcgemperline** [comment]
Hello HJAllen,

I have attached the Win10 dll in this post. I haven't had time to make a pull request. This was compiled a year ago. I think it should still work. Let me know if you have any issues. I am running linux, and github won't let you attach a dll file, I used the linux zip command to zip it up, but this was originally compiled under Windows 10. I think this zip file should work with windows as well. Just uncompress and the dll is in there.
Cheers,

David
[BibTex_DLL.zip](https://github.com/JonnoFTW/BibTeX-Label-Creator/files/1236582/BibTex_DLL.zip)

**Comment by HJAllen** [comment]
Thanks! it worked...

**Comment by dcgemperline** [comment]
No problem!

Thanks for letting me know.

David

**Comment by JonnoFTW** [comment]
Thanks for providing the dll @dcgemperline, I'll add it to the repository. I no longer use Endnote (I switched to Mendeley), so I don't have much motivation to maintain the codebase.
